# FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.14.1_1

FROM eclipse-temurin:21-jdk-alpine

RUN apk update && apk add git

RUN git clone --depth=1 https://github.com/alfredodand/spid-cie-oidc-java && \
	cd spid-cie-oidc-java && \
	chmod +x mvnw && \
	./mvnw clean install

WORKDIR /spid-cie-oidc-java/examples/relying-party-spring-boot

VOLUME ["/data"]

ENV OIDC_HOSTS_TRUST_ANCHOR="trust-anchor.org"
ENV OIDC_HOSTS_CIE_PROVIDER="cie-provider.org"
ENV OIDC_HOSTS_RELYING_PARTY="relying-party.org"
ENV OIDC_RELYING_PARTY_JWK_FED_FILE_PATH="/data/oidc-rp-jwk.json"
ENV OIDC_RELYING_PARTY_CORE_JWK_CORE_FILE_PATH="/data/oidc-rp-core-jwk.json"
ENV OIDC_RELYING_PARTY_TRUST_MARKS_FILE_PATH="/data/oidc-rp-trust-marks.json"
ENV SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS="true"

EXPOSE 5000

ENTRYPOINT ["../../mvnw", "spring-boot:run"]
